# start the dev server and redis
services:
  etl-demo:
    image: node:18-slim
    command: /bin/sh -c "yarn install && yarn dev"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL:
      PORT:
      REDIS_HOST:
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
